name: Fetch Stats
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  collect_stats:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}

      - uses: actions/setup-node@v2
      - run: npm install
      - run: node stats.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Cache stats
